# -*- coding: utf-8 -*-

import json, requests
from bs4 import BeautifulSoup
from util import getnick

def command_how(bot, user, channel, args):
    """".how (steps) - Gives you random instructions from wikiHow, by default 3 steps (generated by http://bifrost.me/wakihow)"""
    if args:
        try:
            times = int(args) if int(args) < 11 else 3
        except:
            times = 3
    else:
        times = 3

    q = bot.get_url("http://bifrost.me/api/steps?count=%s" % times)
    parsed = q.json()

    for i in range(0, times):
        bot.say(channel, "Step %d: %s" % (i + 1, parsed[str(i + 1)]))

def command_why(bot, user, channel, args):
    """.why - Gives a random excuse from http://developerexcuses.com/"""
    page = bot.get_url("http://developerexcuses.com/")
    text = BeautifulSoup(page.text).find("a", {"href": "/"}).text

    bot.say(channel, "%s: %s" % (getnick.get(user), text))
